---
# tasks file for wp-db
- name: delete everything
  command: kubectl delete all --all

- name: creating mysql database pod
  command: kubectl run "{{ db_pod_name }}" --image=mysql:5.7 --env=MYSQL_ROOT_PASSWORD="{{ password }}" --env=MYSQL_DATABASE=db1 --env=MYSQL_USER=shiv --env=MYSQL_PASSWORD="{{ password }}"

- name: creating wordpress pod
  command: kubectl run "{{ wp_pod_name }}" --image=wordpress:5.1.1-php7.3-apache

- name: waiting for IP to comeup
  pause:
    seconds: 60

- name: getting mysql database IP
  command: kubectl get pods -o wide
  register: pods

- name: expose wordpress pod
  command: kubectl expose pods "{{ wp_pod_name }}" --type=NodePort --port=80

- name: get service
  command: kubectl get svc
  register: service

- name: printing exposed service
  debug:
    var: service.stdout

- name: printing pods IP
  debug:
    var: pods.stdout
